// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://emwfjzidmnrjxrttyufd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVtd2ZqemlkbW5yanhydHR5dWZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE2ODgzNDUsImV4cCI6MjA1NzI2NDM0NX0.FOPv9lErMZ97Wk02zO3wbOqQ7HvnolAMcgJgIXX0nmg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);